<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-UPSQUGU" ignored="0" name="Surefire test" tests="9" failures="3" timestamp="2021-04-10T15:00:19 ICT" time="12.023" errors="0">
  <testcase name="@BeforeMethod setupSystemUnderTest" time="6.391" classname="com.jakartalabs.baseui.BaseUITest">
    <failure type="org.openqa.selenium.remote.UnreachableBrowserException" message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: &amp;apos;4.0.0-alpha-7&amp;apos;, revision: &amp;apos;de8579b6d5&amp;apos;
System info: host: &amp;apos;DESKTOP-UPSQUGU&amp;apos;, ip: &amp;apos;192.168.100.26&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_281&amp;apos;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.0.0-alpha-7', revision: 'de8579b6d5'
System info: host: 'DESKTOP-UPSQUGU', ip: '192.168.100.26', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:522)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:127)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
at com.jakartalabs.baseui.BaseUITest.setupSystemUnderTest(BaseUITest.java:41)
at java.util.ArrayList.forEach(ArrayList.java:1259)
Caused by: java.io.UncheckedIOException: java.net.ConnectException: connection timed out: /3.142.218.214:4444
at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:69)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:47)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:60)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:139)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:501)
... 41 more
Caused by: java.net.ConnectException: connection timed out: /3.142.218.214:4444
at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262)
at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /3.142.218.214:4444
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
... 9 more
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setupSystemUnderTest -->
  <testcase name="@AfterMethod cleanup" time="0.001" classname="com.jakartalabs.baseui.BaseUITest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.jakartalabs.baseui.BaseUITest.cleanup(BaseUITest.java:63)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod cleanup -->
  <testcase name="testRegisterAPI" time="3.012" classname="com.jakartalabs.fullstack_answer.TestAPI">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.jakartalabs.utils.APIActions.verifyAPIResponse(APIActions.java:14)
at com.jakartalabs.fullstack_answer.TestAPI.testRegisterAPI(TestAPI.java:23)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testRegisterAPI -->
  <testcase name="testChangeCurrencyAPI" time="1.289" classname="com.jakartalabs.fullstack_answer.TestAPI">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.jakartalabs.utils.APIActions.verifyAPIResponse(APIActions.java:14)
at com.jakartalabs.fullstack_answer.TestAPI.testChangeCurrencyAPI(TestAPI.java:35)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testChangeCurrencyAPI -->
  <testcase name="testCheckSettingAPI" time="0.0" classname="com.jakartalabs.fullstack_answer.TestAPI"/>
  <testcase name="testLogoutAPI" time="1.273" classname="com.jakartalabs.fullstack_answer.TestAPI">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.jakartalabs.utils.APIActions.verifyAPIResponse(APIActions.java:14)
at com.jakartalabs.fullstack_answer.TestAPI.testLogoutAPI(TestAPI.java:52)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testLogoutAPI -->
  <testcase name="test2" time="0.0" classname="com.jakartalabs.fullstack_answer.TestNGExamples"/>
  <testcase name="test2a" time="0.0" classname="com.jakartalabs.fullstack_answer.TestNGExamples"/>
  <testcase name="test2b" time="0.0" classname="com.jakartalabs.fullstack_answer.TestNGExamples"/>
  <testcase name="test1" time="0.0" classname="com.jakartalabs.fullstack_answer.TestNGExamples"/>
  <testcase name="login" time="0.0" classname="com.jakartalabs.fullstack_answer.TestUI">
    <skipped/>
  </testcase> <!-- login -->
</testsuite> <!-- Surefire test -->
